main: me.chickenstyle.luckyblocks.Main
name: LuckyCubes
version: 1.0.2
description: implements cool luckyblocks to the game 
api-version: 1.13
softdepend: [WorldGuard]
commands:
  luckycubes: 
    aliases: lc
    description: Plugin's main command
